version: 2.1
orbs:
  node: circleci/node:8
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test
  release:
    docker:
      - image: node/default
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true
workflows:
    test_and_release:
      jobs:
        - test
        - release:
            requires:
              - test
